import { describe, it, expect, vi, beforeEach } from 'vitest'

const { mockPragma, MockDatabase } = vi.hoisted(() => {
  const mockPragma = vi.fn()
  const MockDatabase = vi.fn(() => ({
    pragma: mockPragma,
    prepare: vi.fn(() => ({
      run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
      get: vi.fn(() => ({ count: 0 })),
      all: vi.fn(() => []),
    })),
    exec: vi.fn(),
    close: vi.fn(),
  }))
  return { mockPragma, MockDatabase }
})

vi.mock('better-sqlite3', () => ({ default: MockDatabase }))

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))

vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/event-bus', () => ({ eventBus: { broadcast: vi.fn(), on: vi.fn() } }))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn((p: string) => `hashed:${p}`) }))
vi.mock('@/lib/logger', () => ({ logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() } }))
vi.mock('@/lib/mentions', () => ({ parseMentions: vi.fn(() => []) }))
vi.mock('@/lib/auto-credentials', () => ({ ensureAutoGeneratedCredentials: vi.fn() }))
vi.mock('@/lib/webhooks', () => ({ initWebhookListener: vi.fn() }))
vi.mock('@/lib/scheduler', () => ({ initScheduler: vi.fn() }))
vi.mock('@/lib/remote-server-bridge', () => ({ startRemoteBridge: vi.fn() }))

describe('SQLite busy_timeout pragma', () => {
  beforeEach(() => {
    vi.resetModules()
    mockPragma.mockClear()
    MockDatabase.mockClear()
  })

  it('sets busy_timeout = 5000 on database initialization', async () => {
    // Fresh module import creates a new db connection
    const { getDatabase } = await import('@/lib/db')
    getDatabase()

    const pragmaCalls = mockPragma.mock.calls.map((c) => c[0] as string)
    expect(pragmaCalls).toContain('busy_timeout = 5000')
  })

  it('sets WAL journal mode on database initialization', async () => {
    const { getDatabase } = await import('@/lib/db')
    getDatabase()

    const pragmaCalls = mockPragma.mock.calls.map((c) => c[0] as string)
    expect(pragmaCalls).toContain('journal_mode = WAL')
  })

  it('skips module-level initialization during build phase', async () => {
    const original = process.env.NEXT_PHASE
    process.env.NEXT_PHASE = 'phase-production-build'
    try {
      // Re-import with build phase set — constructor should not be called at module level
      await import('@/lib/db')
      // The mock may have been called 0 times (no eager init) or once (if getDatabase was called)
      // Key assertion: we don't throw during import in build phase
      expect(true).toBe(true)
    } finally {
      process.env.NEXT_PHASE = original
    }
  })

  it('does not auto-start scheduler or remote bridge in dev by default', async () => {
    const env = process.env as Record<string, string | undefined>
    const originalNodeEnv = env.NODE_ENV
    const originalBuildPhase = env.NEXT_PHASE
    const originalDevFlag = env.MC_ENABLE_BACKGROUND_SERVICES_IN_DEV
    env.NODE_ENV = 'development'
    delete env.NEXT_PHASE
    delete env.MC_ENABLE_BACKGROUND_SERVICES_IN_DEV
    try {
      const { getDatabase } = await import('@/lib/db')
      const scheduler = await import('@/lib/scheduler')
      const bridge = await import('@/lib/remote-server-bridge')
      const schedulerCallsBefore = vi.mocked(scheduler.initScheduler).mock.calls.length
      const bridgeCallsBefore = vi.mocked(bridge.startRemoteBridge).mock.calls.length
      getDatabase()
      const schedulerCallsAfter = vi.mocked(scheduler.initScheduler).mock.calls.length
      const bridgeCallsAfter = vi.mocked(bridge.startRemoteBridge).mock.calls.length
      expect(schedulerCallsAfter).toBe(schedulerCallsBefore)
      expect(bridgeCallsAfter).toBe(bridgeCallsBefore)
    } finally {
      if (originalNodeEnv === undefined) delete env.NODE_ENV
      else env.NODE_ENV = originalNodeEnv
      if (originalBuildPhase === undefined) delete env.NEXT_PHASE
      else env.NEXT_PHASE = originalBuildPhase
      if (originalDevFlag === undefined) delete env.MC_ENABLE_BACKGROUND_SERVICES_IN_DEV
      else env.MC_ENABLE_BACKGROUND_SERVICES_IN_DEV = originalDevFlag
    }
  })

})
