name: OSV Scanner
on:
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        lockfile:
          - mission-control/pnpm-lock.yaml
          - mission-control-client/pnpm-lock.yaml
          - mission-control-tray/pnpm-lock.yaml
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
    with:
      scan-args: --lockfile=./${{ matrix.lockfile }}
      upload-sarif: true
      fail-on-vuln: true
